<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\mDropdownSeries;
class TblDropdownSeries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbl_dropdown_series',function(Blueprint $table){
            $table->increments('id');
            $table->string('BGA');
            $table->string('BGAFP');
            $table->string('LGA');
            $table->string('PGA');
            $table->string('PGALGA');
            $table->string('ProbePin');
            $table->string('PUS');
            $table->string('QFN');
            $table->string('QFP1');
            $table->string('QFP2');
            $table->string('Socket');
            $table->string('SOJ');
            $table->string('SON');
            $table->string('TSOP');
            $table->timestamps();
        });

        mDropdownSeries::create([
            'BGA' => 'BIBGA',
            'BGAFP' => 'NP291',
            'LGA' => 'ACC',
            'PGA' => 'NP236',
            'PGALGA' => 'NP438',
            'PUS' => 'IC149',
            'ProbePin' => '4-Point Dent',
            'QFN' => 'IC549',
            'Socket' => 'ACC',
            'SOJ' => 'IC100',
            'TSOP' => 'IC162',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC280',
            'BGAFP' => 'NP351',
            'LGA' => 'IC273',
            'PGA' => 'NP382',
            'PGALGA' => '',
            'PUS' => '',
            'ProbePin' =>'Press/Roll',
            'QFN' => 'IC550',
            'Socket' => 'AD234',
            'SOJ' => 'IC107',
            'TSOP' => 'IC189',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC398',
            'BGAFP' => 'NP352',
            'LGA' => 'IC280',
            'PGA' => 'NP565',
            'PGALGA' => '',
            'PUS' => '',
            'ProbePin' =>'Spring-Lock',
            'QFN' => 'IC552',
            'Socket' => 'AD51',
            'SOJ' => '',
            'TSOP' => 'IC191',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC409',
            'BGAFP' => 'NP367',
            'LGA' => 'IC405',
            'PGA' => 'NP89',
            'PGALGA' => '',
            'PUS' => '',
            'ProbePin' =>'',
            'QFN' => 'IC553',
            'Socket' => 'ADACC',
            'SOJ' => '',
            'TSOP' => 'IC235',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC449',
            'BGAFP' => 'NP378',
            'LGA' => 'IC569',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '',
            'ProbePin' =>'',
            'QFN' => 'IC564',
            'Socket' => 'IC-102',
            'SOJ' => '',
            'TSOP' => 'IC273',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC501',
            'BGAFP' => 'NP383',
            'LGA' => 'IC807',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '',
            'ProbePin' =>'',
            'QFN' => 'IC-837',
            'Socket' => 'IC-114',
            'SOJ' => '',
            'TSOP' => 'IC296',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC511',
            'BGAFP' => 'NP413',
            'LGA' => 'IC-836',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'IC-857',
            'Socket' => 'IC-115',
            'SOJ' => '',
            'TSOP' => 'IC297',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC530',
            'BGAFP' => 'NP436',
            'LGA' => 'IC-871',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP445',
            'Socket' => 'IC118',
            'SOJ' => '',
            'TSOP' => 'IC354',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC537',
            'BGAFP' => 'NP442',
            'LGA' => 'LGA11',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP473',
            'Socket' => 'IC-120',
            'SOJ' => '',
            'TSOP' => 'IC363',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC538',
            'BGAFP' => 'NP446',
            'LGA' => 'NP364',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP506',
            'Socket' => 'IC121',
            'SOJ' => '',
            'TSOP' => 'IC369',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC542',
            'BGAFP' => 'NP448',
            'LGA' => 'NP404',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP560',
            'Socket' => 'IC-132',
            'SOJ' => '',
            'TSOP' => 'IC385',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC547',
            'BGAFP' => 'NP467',
            'LGA' => 'NP469',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP583',
            'Socket' => 'IC135',
            'SOJ' => '',
            'TSOP' => 'IC389',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC561',
            'BGAFP' => 'NP482',
            'LGA' => 'NP488',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => 'NP584',
            'Socket' => 'IC166',
            'SOJ' => '',
            'TSOP' => 'IC403',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC564',
            'BGAFP' => 'NP494',
            'LGA' => 'NP514',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-176',
            'SOJ' => '',
            'TSOP' => 'IC503',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC567',
            'BGAFP' => 'NP513',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-179',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC-797',
            'BGAFP' => 'NP515',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC200',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'IC-873',
            'BGAFP' => 'NP562',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC203',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP178',
            'BGAFP' => 'NP568',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC211',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP236',
            'BGAFP' => 'NP596',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-214',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP276',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-222',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP352',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-24',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP437',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-258',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP444',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-276',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP481',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-287',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP483',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-299',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP486',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-333',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP504',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-334',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP510',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-336',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP524',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-349',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP537',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC37',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP541',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-377',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP556',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC37F',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP559',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-39',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP563',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-393',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP566',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-401',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP571',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC438',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP587',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-445',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP590',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-46',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'NP595',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-464',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'TCBGA',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC485',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => 'TCLGA',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-487',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-49',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-497',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC499',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-500',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC53',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC558',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC576',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-581',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-589',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC59',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC595',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC601',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC634',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-639',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-657',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-66',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC674',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-699',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC70',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-742',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-746',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-747',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-754',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-755',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-760',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-762',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-776',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-807',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-830',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-832',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-834',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-841',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC848',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-91',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'IC-99',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'ICC34',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'LC030',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'LC050',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'LC-31',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'LCC',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'PS42',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'PS44',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'PS49',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'PS61',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'SMT',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);
        mDropdownSeries::create([
            'BGA' => '',
            'BGAFP' => '',
            'LGA' => '',
            'PGA' => '',
            'PGALGA' => '',
            'PUS' => '  ',
            'ProbePin' =>'',
            'QFN' => '',
            'Socket' => 'TAB',
            'SOJ' => '',
            'TSOP' => '',
            'QFP1' => '',
            'QFP2' => '',
            'SON' => '',
        ]);


    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
